#! /bin/bash

echo -e "\e[30mblack ${1}\e[0m"
echo -e "\e[31mred ${1}\e[0m"
echo -e "\e[32mgreen ${1}\e[0m"
echo -e "\e[33myellow ${1}\e[0m"
echo -e "\e[34mblue ${1}\e[0m"
echo -e "\e[35mmagenta ${1}\e[0m"
echo -e "\e[36mcyan ${1}\e[0m"
echo -e "\e[37mlightGrey ${1}\e[0m"