#!/bin/bash

FILE=$1
Name="${FILE%%.*}"
MainExtension="_main.mp4"
CamExtension="_cam.mp4"
ffmpeg -i $1 -filter:v "crop=850:1080:535:0" $Name$MainExtension
ffmpeg -i $1 -filter:v "crop=376:310:0:410" -an $Name$CamExtension

#"crop=out_w:out_h:x:y"
#out_w is the width of the output rectangle
#out_h is the height of the output rectangle
#x and y specify the top left corner of the output rectangle