#!/bin/bash

FILE=$1
Name="${FILE%%.*}"
MainExtension="_main.mp4"
CamExtension="_cam.mp4"
FeedExtension2="_bigfeed.mp4"
AmmoExtension="_ammo.mp4"
HealthExtension="_health.mp4"
MapExtension="_map.mp4"
ffmpeg -i "$1" -filter:v "crop=850:1080:535:0" "$Name$MainExtension"
ffmpeg -i "$1" -filter:v "crop=353:310:0:410" -an "$Name$CamExtension"
ffmpeg -i "$1" -filter:v "crop=360:170:1555:70" -an "$Name$FeedExtension2"
ffmpeg -i "$1" -filter:v "crop=124:40:1715:1030" -an "$Name$AmmoExtension"
ffmpeg -i "$1" -filter:v "crop=384:40:25:1030" -an "$Name$HealthExtension"
ffmpeg -i "$1" -filter:v "crop=280:280:12:65" -an "$Name$MapExtension"

#"crop=out_w:out_h:x:y"
#out_w is the width of the output rectangle
#out_h is the height of the output rectangle
#x and y specify the top left corner of the output rectangle
