#!/bin/bash

currentBranch="$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')" #Check current branch
echo -e "\e[35m=======================CURRENT BRANCH IS: $currentBranch=======================\e[0m"
IS_MASTER=''
[ "$currentBranch" == "master" ] || [ "$currentBranch" == "develop" ] && IS_MASTER='TRUE'
[ -z "$IS_MASTER" ] && echo -e "\e[33m=======================SWITCHING TO MASTER=======================\e[0m"
[ -z "$IS_MASTER" ] && git stash push -u
[ -z "$IS_MASTER" ] && git checkout master

git pull
git fetch --all -p

[ -z "$IS_MASTER" ] && echo -e "\e[33m=======================SWITCHING BACK TO $currentBranch =======================\e[0m"
[ -z "$IS_MASTER" ] && git checkout $currentBranch
[ -z "$IS_MASTER" ] && git stash pop