#!/bin/bash

currentBranch="$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')" #Check current branch
echo -e "\e[35m=======================CURRENT BRANCH IS: $currentBranch=======================\e[0m"
IS_DEVELOP=''
[ "$currentBranch" == "develop" ] && IS_DEVELOP='TRUE'
[ -z "$IS_DEVELOP" ] && echo -e "\e[33m=======================SWITCHING TO DEVELOP=======================\e[0m"
[ -z "$IS_DEVELOP" ] && git stash push -u
[ -z "$IS_DEVELOP" ] && git checkout develop

git pull
git fetch --all -p

[ -z "$IS_DEVELOP" ] && echo -e "\e[33m=======================SWITCHING BACK TO $currentBranch =======================\e[0m"
[ -z "$IS_DEVELOP" ] && git checkout $currentBranch
[ -z "$IS_DEVELOP" ] && git stash pop