Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install sublimetext3 -y
choco install conemu -y
choco install windirstat -y
choco install adobereader -y
choco install googlechrome -y
choco install firefox -y
choco install winrar -y
choco install vlc -y
choco install git -y
choco install ccleaner -y
choco install vim -y
choco install steam -y
choco install battle.net -y
choco install minecraft -y
choco install epicgameslauncher -y
choco install discord -y
choco install spotify -y
choco install telegram -y
choco install avidemux -y
